### ISSUE TITLE
VVebo修复用户时间线脚本最近不能生效了

### ISSUE THREAD

**Issue by cubeship** [bin64/Scripts#1]

**Comment by nowubh** [comment]
你好，请检查一下你自己的配置，我这里测试了能够正常浏览用户的主页。
![IMG_1371](https://github.com/bin64/Scripts/assets/22713482/565e131e-5876-4693-8959-1e9bb09fc8ab)

**Comment by cubeship** [comment]
好奇怪，重新启用脚本，重装vvebo，依旧不生效
![IMG_1932](https://github.com/bin64/Scripts/assets/19545837/271b332c-f25f-4393-86ce-0403b9c35ea7)
![IMG_1931](https://github.com/bin64/Scripts/assets/19545837/811851ee-43cb-440a-b058-570af98a2a81)

**Comment by nowubh** [comment]
你好，我检查了应该是 Quantumult X 最新版本（1.5.0-830）的引发的这个问题，我已经更新了脚本，你可以更新重新尝试一下。

**Comment by cubeship** [comment]
> 你好，我检查了应该是 Quantumult X 最新版本（1.5.0-830）的引发的这个问题，我已经更新了脚本，你可以更新重新尝试一下。

可以了，感谢大佬👍
